'''
[
  "Django Home",
  "Django Intro",
  "Django Get Started",
  "Create Virtual Environment",
  "Install Django",
  "Django Create Project",
  "Django Create App",
  "Django Views",
  "Django URLs",
  "Django Templates",
  "Django Models",
  "Django Insert Data",
  "Django Update Data",
  "Django Delete Data",
  "Django Update Model",
  "Prep Template and View",
  "Add Link to Details",
  "Add Master Template",
  "Add Main Index Page",
  "Django 404 Template",
  "Add Test View",
  "Django Admin",
  "Create User",
  "Include Models",
  "Set List Display",
  "Update Members",
  "Add Members",
  "Delete Members",
  "Django Variables",
  "Django Tags",
  "Django If Else",
  "Django For Loop",
  "Django Comment",
  "Django Include",
  "QuerySet Introduction",
  "QuerySet Get",
  "QuerySet Filter",
  "QuerySet Order By",
  "Add Static Files",
  "Install WhiteNoise",
  "Collect Static Files",
  "Add Global Static Files",
  "Add Styles to the Project",
  "PostgreSQL Intro",
  "Create AWS Account",
  "Create Database in RDS",
  "Connect to Database",
  "Add Members",
  "Elastic Beanstalk (EB)",
  "Create requirements.txt",
  "Create django.config",
  "Create .zip File",
  "Deploy with EB",
  "Update Project",
  "Add Slug Field",
  "Add Bootstrap 5",
  "Template Tag Reference",
  "Filter Reference",
  "Field lookups Reference",
  "Django Compiler",
  "Django Exercises",
  "Django Quiz",
  "Django Server",
  "Django Certificate"
]
'''