/*
[
  "Kotlin HOME",
  "Kotlin Intro",
  "Kotlin Get Started",
  "Kotlin Syntax",
  "Kotlin Output",
  "Kotlin Comments",
  "Kotlin Variables",
  "Kotlin Data Types",
  "Kotlin Operators",
  "Kotlin Strings",
  "Kotlin Booleans",
  "Kotlin If...Else",
  "Kotlin When",
  "Kotlin While Loop",
  "Kotlin Break/Continue",
  "Kotlin Arrays",
  "Kotlin For Loop",
  "Kotlin Ranges",
  "Kotlin Functions",
  "Kotlin OOP",
  "Kotlin Classes/Objects",
  "Kotlin Constructors",
  "Kotlin Class Functions",
  "Kotlin Inheritance",
  "Kotlin Examples",
  "Kotlin Exercises",
  "Kotlin Quiz",
  "Kotlin Certificate",
  "Kotlin Compiler"
]
*/