'''
[
  "NumPy HOME",
  "NumPy Intro",
  "NumPy Getting Started",
  "NumPy Creating Arrays",
  "NumPy Array Indexing",
  "NumPy Array Slicing",
  "NumPy Data Types",
  "NumPy Copy vs View",
  "NumPy Array Shape",
  "NumPy Array Reshape",
  "NumPy Array Iterating",
  "NumPy Array Join",
  "NumPy Array Split",
  "NumPy Array Search",
  "NumPy Array Sort",
  "NumPy Array Filter",
  "Random Intro",
  "Data Distribution",
  "Random Permutation",
  "Seaborn Module",
  "Normal Distribution",
  "Binomial Distribution",
  "Poisson Distribution",
  "Uniform Distribution",
  "Logistic Distribution",
  "Multinomial Distribution",
  "Exponential Distribution",
  "Chi Square Distribution",
  "Rayleigh Distribution",
  "Pareto Distribution",
  "Zipf Distribution",
  "ufunc Intro",
  "ufunc Create Function",
  "ufunc Simple Arithmetic",
  "ufunc Rounding Decimals",
  "ufunc Logs",
  "ufunc Summations",
  "ufunc Products",
  "ufunc Differences",
  "ufunc Finding LCM",
  "ufunc Finding GCD",
  "ufunc Trigonometric",
  "ufunc Hyperbolic",
  "ufunc Set Operations",
  "NumPy Editor",
  "NumPy Quiz",
  "NumPy Exercises",
  "NumPy Certificate"
]
'''