'''
[
  "Python HOME",
  "Python Intro",
  "Python Get Started",
  "Python Syntax",
  "Python Comments",
  "Python Variables",
  "Python Data Types",
  "Python Numbers",
  "Python Casting",
  "Python Strings",
  "Python Booleans",
  "Python Operators",
  "Python Lists",
  "Python Tuples",
  "Python Sets",
  "Python Dictionaries",
  "Python If...Else",
  "Python While Loops",
  "Python For Loops",
  "Python Functions",
  "Python Lambda",
  "Python Arrays",
  "Python Classes/Objects",
  "Python Inheritance",
  "Python Iterators",
  "Python Polymorphism",
  "Python Scope",
  "Python Modules",
  "Python Dates",
  "Python Math",
  "Python JSON",
  "Python RegEx",
  "Python PIP",
  "Python Try...Except",
  "Python User Input",
  "Python String Formatting",
  "Python File Handling",
  "Python Read Files",
  "Python Write/Create Files",
  "Python Delete Files",
  "NumPy Tutorial",
  "Pandas Tutorial",
  "SciPy Tutorial",
  "Django Tutorial",
  "Matplotlib Intro",
  "Matplotlib Get Started",
  "Matplotlib Pyplot",
  "Matplotlib Plotting",
  "Matplotlib Markers",
  "Matplotlib Line",
  "Matplotlib Labels",
  "Matplotlib Grid",
  "Matplotlib Subplot",
  "Matplotlib Scatter",
  "Matplotlib Bars",
  "Matplotlib Histograms",
  "Matplotlib Pie Charts",
  "Getting Started",
  "Mean Median Mode",
  "Standard Deviation",
  "Percentile",
  "Data Distribution",
  "Normal Data Distribution",
  "Scatter Plot",
  "Linear Regression",
  "Polynomial Regression",
  "Multiple Regression",
  "Scale",
  "Train/Test",
  "Decision Tree",
  "Confusion Matrix",
  "Hierarchical Clustering",
  "Logistic Regression",
  "Grid Search",
  "Categorical Data",
  "K-means",
  "Bootstrap Aggregation",
  "Cross Validation",
  "AUC - ROC Curve",
  "K-nearest neighbors",
  "MySQL Get Started",
  "MySQL Create Database",
  "MySQL Create Table",
  "MySQL Insert",
  "MySQL Select",
  "MySQL Where",
  "MySQL Order By",
  "MySQL Delete",
  "MySQL Drop Table",
  "MySQL Update",
  "MySQL Limit",
  "MySQL Join",
  "MongoDB Get Started",
  "MongoDB Create DB",
  "MongoDB Collection",
  "MongoDB Insert",
  "MongoDB Find",
  "MongoDB Query",
  "MongoDB Sort",
  "MongoDB Delete",
  "MongoDB Drop Collection",
  "MongoDB Update",
  "MongoDB Limit",
  "Python Overview",
  "Python Built-in Functions",
  "Python String Methods",
  "Python List Methods",
  "Python Dictionary Methods",
  "Python Tuple Methods",
  "Python Set Methods",
  "Python File Methods",
  "Python Keywords",
  "Python Exceptions",
  "Python Glossary",
  "Random Module",
  "Requests Module",
  "Statistics Module",
  "Math Module",
  "cMath Module",
  "Remove List Duplicates",
  "Reverse a String",
  "Add Two Numbers",
  "Python Examples",
  "Python Compiler",
  "Python Exercises",
  "Python Quiz",
  "Python Server",
  "Python Bootcamp",
  "Python Certificate"
]
'''