/*
[
  "React Home",
  "React Intro",
  "React Get Started",
  "React Upgrade",
  "React ES6",
  "React Render HTML",
  "React JSX",
  "React Components",
  "React Class",
  "React Props",
  "React Events",
  "React Conditionals",
  "React Lists",
  "React Forms",
  "React Router",
  "React Memo",
  "React CSS Styling",
  "React Sass Styling",
  "What is a Hook?",
  "useState",
  "useEffect",
  "useContext",
  "useRef",
  "useReducer",
  "useCallback",
  "useMemo",
  "Custom Hooks",
  "React Compiler",
  "React Quiz",
  "React Exercises",
  "React Server",
  "React Certificate"
]
*/